feat(init-setup.md): Instructions for initial setup added
z1digitalstudio/developers-handbook pull request #1
Opened 2020-03-02 12:07 UTC by alvaroquilez

## 📝 Description

## 🚨 How Has This Been Tested?

## ✅ Checklist:

- [ ] My pull requests is small enough so it can be easily reviewed. [g006](https://github.com/z1digitalstudio/developers-handbook#rule-g006) 
- [ ] All my commits or even all commits message styles matches our requested structure. [g007](https://github.com/z1digitalstudio/developers-handbook#rule-g007)
- [ ] My code is not introducing any compiler warnings.
- [ ] My code compile properly.
- [ ] My code doesn't break unit tests or linting checks.

2020-03-02 14:10 UTC, IvanCoronado requested changes

2020-03-02 14:10 UTC, IvanCoronado commented on docs/init-setup.md
> +### Git (optional)
Vamos a quitar el optional, habría que instalarlo de todos modos

2020-03-02 14:10 UTC, IvanCoronado commented on docs/init-setup.md
> +[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
Podemos poner aquí directamente el comando que copia eso en ese fichero?

2020-03-02 14:10 UTC, IvanCoronado commented on docs/init-setup.md
> +- SSH Key
Vamos a ordenar esto correctamente como viene abajo y a enlazarlo con cada una de las secciones

2020-03-03 09:05 UTC, IvanCoronado commented on init-setup.md
> +touch ~/.zshrc & echo 'source "$HOME/.nvm/nvm.sh"' >> ~/.zshrc
Una duda @juanjosevilchezn si no tenemos la consola de zshrc esto no hay que hacerlo no?

2020-03-03 09:11 UTC, juanjosevilchezn commented on init-setup.md
> +touch ~/.zshrc & echo 'source "$HOME/.nvm/nvm.sh"' >> ~/.zshrc
Estás en lo cierto, no es necesario hacerlo si no estás utilizando zsh aunque desconozco si hubiese que hacerlo si utilizamos bash en el .bashrc.

De igual forma, actualizo ahora mismo con esta información.

2020-03-03 09:20 UTC, IvanCoronado commented on init-setup.md
> +touch ~/.zshrc & echo 'source "$HOME/.nvm/nvm.sh"' >> ~/.zshrc
Perfect, mejor ahora

2020-03-03 09:21 UTC, merged